### ISSUE TITLE
color assigned to a team, not all teams

### ISSUE THREAD

**Issue by tylerjnorton** [acoll/triviarator#13]
When a team gets a question right, their color spreads to the headers of all the teams. This is obviously an issue.

**Comment by acoll** [comment]
haha. sweet. i'll fix that. Its sort of like the team is marking their
territory

**Comment by acoll** [comment]
false

**Comment by tylerjnorton** [comment]
Bears, Beets, Batlestar Galactica

**Comment by tylerjnorton** [comment]
"When a team gets a question right,"
